#
# Copyright (c) 2019 Hiroshi Hayakawa <hhiroshell@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# --- Build the application as GraalVM Native Image. ---
FROM oracle/graalvm-ce:19.1.1 AS native-image-builder

WORKDIR /mvn

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
COPY ./pom.xml ./pom.xml
COPY ./mvnw ./mvnw
COPY ./.mvn ./.mvn
RUN ./mvnw package -Pnative-image -Dnative.image.skip -DskipTests

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
RUN gu install native-image
COPY ./src ./src
RUN ./mvnw package -Pnative-image -Dnative.image.buildStatic

# --- Build an application container ---
FROM debian:buster-slim

RUN groupadd -g 61000 cowweb && \
    useradd -g 61000 -l -M -s /bin/false -u 61000 cowweb

RUN mkdir /app
COPY --from=native-image-builder --chown=cowweb:cowweb /mvn/target/cowweb /app/cowweb

USER cowweb
ENTRYPOINT ["/app/cowweb"]
EXPOSE 8080
